#!/bin/bash
# 示例 10: 综合完整示例
# 展示一个完整的、生产环境可用的配置

echo "=========================================="
echo "示例 10: 综合完整示例"
echo "=========================================="
echo ""

echo "10.1 深度学习训练分析（推荐配置）"
echo "命令:"
echo "nsys profile \\"
echo "  --trace=cuda,nvtx,osrt \\"
echo "  --cuda-memory-usage=true \\"
echo "  --sampling-frequency=1000 \\"
echo "  --gpu-metrics-frequency=100 \\"
echo "  --stats=true \\"
echo "  --force-overwrite=true \\"
echo "  --output=training_profile.nsys-rep \\"
echo "  python train.py"
echo ""
echo "说明:"
echo "  - 跟踪 CUDA、NVTX 和 OS 运行时"
echo "  - 启用内存跟踪"
echo "  - 高频率采样以获得详细信息"
echo "  - 显示统计摘要"
echo ""

echo "10.2 快速性能检查（轻量级）"
echo "命令:"
echo "nsys profile \\"
echo "  --trace=cuda,nvtx \\"
echo "  --sampling-frequency=100 \\"
echo "  --duration=10 \\"
echo "  --output=quick_check.nsys-rep \\"
echo "  python script.py"
echo ""
echo "说明:"
echo "  - 只跟踪 CUDA 和 NVTX"
echo "  - 低采样频率，文件更小"
echo "  - 只分析前 10 秒"
echo ""

echo "10.3 内存泄漏检测"
echo "命令:"
echo "nsys profile \\"
echo "  --trace=cuda \\"
echo "  --cuda-memory-usage=true \\"
echo "  --sampling-frequency=1000 \\"
echo "  --duration=60 \\"
echo "  --output=memory_leak.nsys-rep \\"
echo "  python script.py"
echo ""
echo "说明:"
echo "  - 专注于内存跟踪"
echo "  - 长时间分析以检测泄漏"
echo ""

echo "实际使用示例:"
echo "  nsys profile \\"
echo "    --trace=cuda,nvtx \\"
echo "    --cuda-memory-usage=true \\"
echo "    --sampling-frequency=1000 \\"
echo "    --stats=true \\"
echo "    --force-overwrite=true \\"
echo "    --output=nsys_profiles/comprehensive.nsys-rep \\"
echo "    python nvtx_tag_demo.py"
echo ""

